// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/netlinkwrapper (interfaces: NetLink)

// Package mock_netlinkwrapper is a generated GoMock package.
package mock_netlinkwrapper

import (
	gomock "github.com/golang/mock/gomock"
	netlink "github.com/vishvananda/netlink"
)

// MockNetLink is a mock of NetLink interface.
type MockNetLink struct {
	ctrl     *gomock.Controller
	recorder *MockNetLinkMockRecorder
}

// MockNetLinkMockRecorder is the mock recorder for MockNetLink.
type MockNetLinkMockRecorder struct {
	mock *MockNetLink
}

// NewMockNetLink creates a new mock instance.
func NewMockNetLink(ctrl *gomock.Controller) *MockNetLink { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetLink) EXPECT() *MockNetLinkMockRecorder {
	_ = "STUB: not implemented"

	// AddrAdd mocks base method.
	return nil
}

func (m *MockNetLink) AddrAdd(arg0 netlink.Link, arg1 *netlink.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// AddrAdd indicates an expected call of AddrAdd.
func (mr *MockNetLinkMockRecorder) AddrAdd(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddrDel mocks base method.
func (m *MockNetLink) AddrDel(arg0 netlink.Link, arg1 *netlink.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// AddrDel indicates an expected call of AddrDel.
func (mr *MockNetLinkMockRecorder) AddrDel(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddrList mocks base method.
func (m *MockNetLink) AddrList(arg0 netlink.Link, arg1 int) ([]netlink.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddrList indicates an expected call of AddrList.
func (mr *MockNetLinkMockRecorder) AddrList(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkAdd mocks base method.
func (m *MockNetLink) LinkAdd(arg0 netlink.Link) error { _ = "STUB: not implemented"; return nil }

// LinkAdd indicates an expected call of LinkAdd.
func (mr *MockNetLinkMockRecorder) LinkAdd(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkByName mocks base method.
func (m *MockNetLink) LinkByName(arg0 string) (netlink.Link, error) {
	_ = "STUB: not implemented"
	return *new(netlink.Link), nil
}

// LinkByName indicates an expected call of LinkByName.
func (mr *MockNetLinkMockRecorder) LinkByName(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkDel mocks base method.
func (m *MockNetLink) LinkDel(arg0 netlink.Link) error { _ = "STUB: not implemented"; return nil }

// LinkDel indicates an expected call of LinkDel.
func (mr *MockNetLinkMockRecorder) LinkDel(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkList mocks base method.
func (m *MockNetLink) LinkList() ([]netlink.Link, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LinkList indicates an expected call of LinkList.
func (mr *MockNetLinkMockRecorder) LinkList() *gomock.Call { _ = "STUB: not implemented"; return nil }

// LinkSetDown mocks base method.
func (m *MockNetLink) LinkSetDown(arg0 netlink.Link) error { _ = "STUB: not implemented"; return nil }

// LinkSetDown indicates an expected call of LinkSetDown.
func (mr *MockNetLinkMockRecorder) LinkSetDown(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetMTU mocks base method.
func (m *MockNetLink) LinkSetMTU(arg0 netlink.Link, arg1 int) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetMTU indicates an expected call of LinkSetMTU.
func (mr *MockNetLinkMockRecorder) LinkSetMTU(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetNsFd mocks base method.
func (m *MockNetLink) LinkSetNsFd(arg0 netlink.Link, arg1 int) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetNsFd indicates an expected call of LinkSetNsFd.
func (mr *MockNetLinkMockRecorder) LinkSetNsFd(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetUp mocks base method.
func (m *MockNetLink) LinkSetUp(arg0 netlink.Link) error { _ = "STUB: not implemented"; return nil }

// LinkSetUp indicates an expected call of LinkSetUp.
func (mr *MockNetLinkMockRecorder) LinkSetUp(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NeighAdd mocks base method.
func (m *MockNetLink) NeighAdd(arg0 *netlink.Neigh) error { _ = "STUB: not implemented"; return nil }

// NeighAdd indicates an expected call of NeighAdd.
func (mr *MockNetLinkMockRecorder) NeighAdd(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewRule mocks base method.
func (m *MockNetLink) NewRule() *netlink.Rule { _ = "STUB: not implemented"; return nil }

// NewRule indicates an expected call of NewRule.
func (mr *MockNetLinkMockRecorder) NewRule() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ParseAddr mocks base method.
func (m *MockNetLink) ParseAddr(arg0 string) (*netlink.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseAddr indicates an expected call of ParseAddr.
func (mr *MockNetLinkMockRecorder) ParseAddr(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteAdd mocks base method.
func (m *MockNetLink) RouteAdd(arg0 *netlink.Route) error { _ = "STUB: not implemented"; return nil }

// RouteAdd indicates an expected call of RouteAdd.
func (mr *MockNetLinkMockRecorder) RouteAdd(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteDel mocks base method.
func (m *MockNetLink) RouteDel(arg0 *netlink.Route) error { _ = "STUB: not implemented"; return nil }

// RouteDel indicates an expected call of RouteDel.
func (mr *MockNetLinkMockRecorder) RouteDel(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteList mocks base method.
func (m *MockNetLink) RouteList(arg0 netlink.Link, arg1 int) ([]netlink.Route, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RouteList indicates an expected call of RouteList.
func (mr *MockNetLinkMockRecorder) RouteList(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteReplace mocks base method.
func (m *MockNetLink) RouteReplace(arg0 *netlink.Route) error {
	_ = "STUB: not implemented"
	return nil
}

// RouteReplace indicates an expected call of RouteReplace.
func (mr *MockNetLinkMockRecorder) RouteReplace(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuleAdd mocks base method.
func (m *MockNetLink) RuleAdd(arg0 *netlink.Rule) error { _ = "STUB: not implemented"; return nil }

// RuleAdd indicates an expected call of RuleAdd.
func (mr *MockNetLinkMockRecorder) RuleAdd(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuleDel mocks base method.
func (m *MockNetLink) RuleDel(arg0 *netlink.Rule) error { _ = "STUB: not implemented"; return nil }

// RuleDel indicates an expected call of RuleDel.
func (mr *MockNetLinkMockRecorder) RuleDel(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuleList mocks base method.
func (m *MockNetLink) RuleList(arg0 int) ([]netlink.Rule, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RuleList indicates an expected call of RuleList.
func (mr *MockNetLinkMockRecorder) RuleList(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
