// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/grpcwrapper (interfaces: GRPC)

// Package mock_grpcwrapper is a generated GoMock package.
package mock_grpcwrapper

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGRPC is a mock of GRPC interface.
type MockGRPC struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCMockRecorder
}

// MockGRPCMockRecorder is the mock recorder for MockGRPC.
type MockGRPCMockRecorder struct {
	mock *MockGRPC
}

// NewMockGRPC creates a new mock instance.
func NewMockGRPC(ctrl *gomock.Controller) *MockGRPC { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPC) EXPECT() *MockGRPCMockRecorder {
	_ = "STUB: not implemented"

	// Dial mocks base method.
	return nil
}

func (m *MockGRPC) Dial(arg0 string, arg1 ...grpc.DialOption) (*grpc.ClientConn, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Dial indicates an expected call of Dial.
func (mr *MockGRPCMockRecorder) Dial(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DialContext mocks base method.
func (m *MockGRPC) DialContext(arg0 context.Context, arg1 string, arg2 ...grpc.DialOption) (*grpc.ClientConn, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DialContext indicates an expected call of DialContext.
func (mr *MockGRPCMockRecorder) DialContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
