// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/ipwrapper (interfaces: IP)

// Package mock_ipwrapper is a generated GoMock package.
package mock_ipwrapper

import (
	net "net"

	gomock "github.com/golang/mock/gomock"
	netlink "github.com/vishvananda/netlink"
)

// MockIP is a mock of IP interface.
type MockIP struct {
	ctrl     *gomock.Controller
	recorder *MockIPMockRecorder
}

// MockIPMockRecorder is the mock recorder for MockIP.
type MockIPMockRecorder struct {
	mock *MockIP
}

// NewMockIP creates a new mock instance.
func NewMockIP(ctrl *gomock.Controller) *MockIP { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIP) EXPECT() *MockIPMockRecorder {
	_ = "STUB: not implemented"

	// AddDefaultRoute mocks base method.
	return nil
}

func (m *MockIP) AddDefaultRoute(arg0 net.IP, arg1 netlink.Link) error {
	_ = "STUB: not implemented"
	return nil
}

// AddDefaultRoute indicates an expected call of AddDefaultRoute.
func (mr *MockIPMockRecorder) AddDefaultRoute(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
