// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/iptableswrapper (interfaces: IPTablesIface)

// Package mock_iptableswrapper is a generated GoMock package.
package mock_iptableswrapper

import (
	gomock "github.com/golang/mock/gomock"
)

// MockIPTablesIface is a mock of IPTablesIface interface.
type MockIPTablesIface struct {
	ctrl     *gomock.Controller
	recorder *MockIPTablesIfaceMockRecorder
}

// MockIPTablesIfaceMockRecorder is the mock recorder for MockIPTablesIface.
type MockIPTablesIfaceMockRecorder struct {
	mock *MockIPTablesIface
}

// NewMockIPTablesIface creates a new mock instance.
func NewMockIPTablesIface(ctrl *gomock.Controller) *MockIPTablesIface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPTablesIface) EXPECT() *MockIPTablesIfaceMockRecorder {
	_ = "STUB: not implemented"

	// Append mocks base method.
	return nil
}

func (m *MockIPTablesIface) Append(arg0, arg1 string, arg2 ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Append indicates an expected call of Append.
func (mr *MockIPTablesIfaceMockRecorder) Append(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppendUnique mocks base method.
func (m *MockIPTablesIface) AppendUnique(arg0, arg1 string, arg2 ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// AppendUnique indicates an expected call of AppendUnique.
func (mr *MockIPTablesIfaceMockRecorder) AppendUnique(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ChainExists mocks base method.
func (m *MockIPTablesIface) ChainExists(arg0, arg1 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// ChainExists indicates an expected call of ChainExists.
func (mr *MockIPTablesIfaceMockRecorder) ChainExists(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ClearChain mocks base method.
func (m *MockIPTablesIface) ClearChain(arg0, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// ClearChain indicates an expected call of ClearChain.
func (mr *MockIPTablesIfaceMockRecorder) ClearChain(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockIPTablesIface) Delete(arg0, arg1 string, arg2 ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockIPTablesIfaceMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteChain mocks base method.
func (m *MockIPTablesIface) DeleteChain(arg0, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteChain indicates an expected call of DeleteChain.
func (mr *MockIPTablesIfaceMockRecorder) DeleteChain(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Exists mocks base method.
func (m *MockIPTablesIface) Exists(arg0, arg1 string, arg2 ...string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Exists indicates an expected call of Exists.
func (mr *MockIPTablesIfaceMockRecorder) Exists(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HasRandomFully mocks base method.
func (m *MockIPTablesIface) HasRandomFully() bool { _ = "STUB: not implemented"; return false }

// HasRandomFully indicates an expected call of HasRandomFully.
func (mr *MockIPTablesIfaceMockRecorder) HasRandomFully() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Insert mocks base method.
func (m *MockIPTablesIface) Insert(arg0, arg1 string, arg2 int, arg3 ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Insert indicates an expected call of Insert.
func (mr *MockIPTablesIfaceMockRecorder) Insert(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockIPTablesIface) List(arg0, arg1 string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List indicates an expected call of List.
func (mr *MockIPTablesIfaceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListChains mocks base method.
func (m *MockIPTablesIface) ListChains(arg0 string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListChains indicates an expected call of ListChains.
func (mr *MockIPTablesIfaceMockRecorder) ListChains(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewChain mocks base method.
func (m *MockIPTablesIface) NewChain(arg0, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// NewChain indicates an expected call of NewChain.
func (mr *MockIPTablesIfaceMockRecorder) NewChain(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
