// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/utils/ttime (interfaces: Time,Timer)

// Package mock_ttime is a generated GoMock package.
package mock_ttime

import (
	time "time"

	ttime "github.com/aws/amazon-vpc-cni-k8s/pkg/utils/ttime"
	gomock "github.com/golang/mock/gomock"
)

// MockTime is a mock of Time interface.
type MockTime struct {
	ctrl     *gomock.Controller
	recorder *MockTimeMockRecorder
}

// MockTimeMockRecorder is the mock recorder for MockTime.
type MockTimeMockRecorder struct {
	mock *MockTime
}

// NewMockTime creates a new mock instance.
func NewMockTime(ctrl *gomock.Controller) *MockTime { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTime) EXPECT() *MockTimeMockRecorder {
	_ = "STUB: not implemented"

	// After mocks base method.
	return nil
}

func (m *MockTime) After(arg0 time.Duration) <-chan time.Time {
	_ = "STUB: not implemented"
	return nil
}

// After indicates an expected call of After.
func (mr *MockTimeMockRecorder) After(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AfterFunc mocks base method.
func (m *MockTime) AfterFunc(arg0 time.Duration, arg1 func()) ttime.Timer {
	_ = "STUB: not implemented"
	return *new(ttime.Timer)
}

// AfterFunc indicates an expected call of AfterFunc.
func (mr *MockTimeMockRecorder) AfterFunc(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Now mocks base method.
func (m *MockTime) Now() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Now indicates an expected call of Now.
func (mr *MockTimeMockRecorder) Now() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Sleep mocks base method.
func (m *MockTime) Sleep(arg0 time.Duration) { _ = "STUB: not implemented"; return }

// Sleep indicates an expected call of Sleep.
func (mr *MockTimeMockRecorder) Sleep(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTimer is a mock of Timer interface.
type MockTimer struct {
	ctrl     *gomock.Controller
	recorder *MockTimerMockRecorder
}

// MockTimerMockRecorder is the mock recorder for MockTimer.
type MockTimerMockRecorder struct {
	mock *MockTimer
}

// NewMockTimer creates a new mock instance.
func NewMockTimer(ctrl *gomock.Controller) *MockTimer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimer) EXPECT() *MockTimerMockRecorder {
	_ = "STUB: not implemented"

	// Reset mocks base method.
	return nil
}

func (m *MockTimer) Reset(arg0 time.Duration) bool { _ = "STUB: not implemented"; return false }

// Reset indicates an expected call of Reset.
func (mr *MockTimerMockRecorder) Reset(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockTimer) Stop() bool { _ = "STUB: not implemented"; return false }

// Stop indicates an expected call of Stop.
func (mr *MockTimerMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
