// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go

// Package mock_publisher is a generated GoMock package.
package mock_publisher

import (
	context "context"

	cloudwatch "github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	types "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	gomock "github.com/golang/mock/gomock"
)

// MockcloudWatchAPI is a mock of cloudWatchAPI interface.
type MockcloudWatchAPI struct {
	ctrl     *gomock.Controller
	recorder *MockcloudWatchAPIMockRecorder
}

// MockcloudWatchAPIMockRecorder is the mock recorder for MockcloudWatchAPI.
type MockcloudWatchAPIMockRecorder struct {
	mock *MockcloudWatchAPI
}

// NewMockcloudWatchAPI creates a new mock instance.
func NewMockcloudWatchAPI(ctrl *gomock.Controller) *MockcloudWatchAPI {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcloudWatchAPI) EXPECT() *MockcloudWatchAPIMockRecorder {
	_ = "STUB: not implemented"

	// PutMetricData mocks base method.
	return nil
}

func (m *MockcloudWatchAPI) PutMetricData(ctx context.Context, params *cloudwatch.PutMetricDataInput, optFns ...func(*cloudwatch.Options)) (*cloudwatch.PutMetricDataOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutMetricData indicates an expected call of PutMetricData.
func (mr *MockcloudWatchAPIMockRecorder) PutMetricData(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	_ = "STUB: not implemented"

	// Publish mocks base method.
	return nil
}

func (m *MockPublisher) Publish(metricsDataPoints ...types.MetricDatum) {
	_ = "STUB: not implemented"
	return
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(metricsDataPoints ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockPublisher) Start(publishInterval int) { _ = "STUB: not implemented"; return }

// Start indicates an expected call of Start.
func (mr *MockPublisherMockRecorder) Start(publishInterval interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockPublisher) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockPublisherMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
