// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/rpc (interfaces: CNIBackendClient,NPBackendClient,ConfigServerBackendClient)

// Package mock_rpc is a generated GoMock package.
package mock_rpc

import (
	context "context"

	rpc "github.com/aws/amazon-vpc-cni-k8s/rpc"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCNIBackendClient is a mock of CNIBackendClient interface.
type MockCNIBackendClient struct {
	ctrl     *gomock.Controller
	recorder *MockCNIBackendClientMockRecorder
}

// MockCNIBackendClientMockRecorder is the mock recorder for MockCNIBackendClient.
type MockCNIBackendClientMockRecorder struct {
	mock *MockCNIBackendClient
}

// NewMockCNIBackendClient creates a new mock instance.
func NewMockCNIBackendClient(ctrl *gomock.Controller) *MockCNIBackendClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCNIBackendClient) EXPECT() *MockCNIBackendClientMockRecorder {
	_ = "STUB: not implemented"

	// AddNetwork mocks base method.
	return nil
}

func (m *MockCNIBackendClient) AddNetwork(arg0 context.Context, arg1 *rpc.AddNetworkRequest, arg2 ...grpc.CallOption) (*rpc.AddNetworkReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddNetwork indicates an expected call of AddNetwork.
func (mr *MockCNIBackendClientMockRecorder) AddNetwork(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DelNetwork mocks base method.
func (m *MockCNIBackendClient) DelNetwork(arg0 context.Context, arg1 *rpc.DelNetworkRequest, arg2 ...grpc.CallOption) (*rpc.DelNetworkReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DelNetwork indicates an expected call of DelNetwork.
func (mr *MockCNIBackendClientMockRecorder) DelNetwork(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockNPBackendClient is a mock of NPBackendClient interface.
type MockNPBackendClient struct {
	ctrl     *gomock.Controller
	recorder *MockNPBackendClientMockRecorder
}

// MockNPBackendClientMockRecorder is the mock recorder for MockNPBackendClient.
type MockNPBackendClientMockRecorder struct {
	mock *MockNPBackendClient
}

// NewMockNPBackendClient creates a new mock instance.
func NewMockNPBackendClient(ctrl *gomock.Controller) *MockNPBackendClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNPBackendClient) EXPECT() *MockNPBackendClientMockRecorder {
	_ = "STUB: not implemented"

	// DeletePodNp mocks base method.
	return nil
}

func (m *MockNPBackendClient) DeletePodNp(arg0 context.Context, arg1 *rpc.DeleteNpRequest, arg2 ...grpc.CallOption) (*rpc.DeleteNpReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePodNp indicates an expected call of DeletePodNp.
func (mr *MockNPBackendClientMockRecorder) DeletePodNp(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EnforceNpToPod mocks base method.
func (m *MockNPBackendClient) EnforceNpToPod(arg0 context.Context, arg1 *rpc.EnforceNpRequest, arg2 ...grpc.CallOption) (*rpc.EnforceNpReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnforceNpToPod indicates an expected call of EnforceNpToPod.
func (mr *MockNPBackendClientMockRecorder) EnforceNpToPod(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockConfigServerBackendClient is a mock of ConfigServerBackendClient interface.
type MockConfigServerBackendClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServerBackendClientMockRecorder
}

// MockConfigServerBackendClientMockRecorder is the mock recorder for MockConfigServerBackendClient.
type MockConfigServerBackendClientMockRecorder struct {
	mock *MockConfigServerBackendClient
}

// NewMockConfigServerBackendClient creates a new mock instance.
func NewMockConfigServerBackendClient(ctrl *gomock.Controller) *MockConfigServerBackendClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigServerBackendClient) EXPECT() *MockConfigServerBackendClientMockRecorder {
	_ = "STUB: not implemented"

	// GetNetworkPolicyConfigs mocks base method.
	return nil
}

func (m *MockConfigServerBackendClient) GetNetworkPolicyConfigs(arg0 context.Context, arg1 *emptypb.Empty, arg2 ...grpc.CallOption) (*rpc.NetworkPolicyAgentConfigReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNetworkPolicyConfigs indicates an expected call of GetNetworkPolicyConfigs.
func (mr *MockConfigServerBackendClientMockRecorder) GetNetworkPolicyConfigs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
