// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/networkutils (interfaces: NetworkAPIs)

// Package mock_networkutils is a generated GoMock package.
package mock_networkutils

import (
	net "net"
	time "time"

	gomock "github.com/golang/mock/gomock"
	netlink "github.com/vishvananda/netlink"
)

// MockNetworkAPIs is a mock of NetworkAPIs interface.
type MockNetworkAPIs struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkAPIsMockRecorder
}

// MockNetworkAPIsMockRecorder is the mock recorder for MockNetworkAPIs.
type MockNetworkAPIsMockRecorder struct {
	mock *MockNetworkAPIs
}

// NewMockNetworkAPIs creates a new mock instance.
func NewMockNetworkAPIs(ctrl *gomock.Controller) *MockNetworkAPIs {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkAPIs) EXPECT() *MockNetworkAPIsMockRecorder {
	_ = "STUB: not implemented"

	// CleanUpStaleAWSChains mocks base method.
	return nil
}

func (m *MockNetworkAPIs) CleanUpStaleAWSChains(arg0, arg1 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// CleanUpStaleAWSChains indicates an expected call of CleanUpStaleAWSChains.
func (mr *MockNetworkAPIsMockRecorder) CleanUpStaleAWSChains(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRulesBySrc mocks base method.
func (m *MockNetworkAPIs) DeleteRulesBySrc(arg0 string, arg1 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRulesBySrc indicates an expected call of DeleteRulesBySrc.
func (mr *MockNetworkAPIsMockRecorder) DeleteRulesBySrc(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetExcludeSNATCIDRs mocks base method.
func (m *MockNetworkAPIs) GetExcludeSNATCIDRs() []string { _ = "STUB: not implemented"; return nil }

// GetExcludeSNATCIDRs indicates an expected call of GetExcludeSNATCIDRs.
func (mr *MockNetworkAPIsMockRecorder) GetExcludeSNATCIDRs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetExternalServiceCIDRs mocks base method.
func (m *MockNetworkAPIs) GetExternalServiceCIDRs() []string { _ = "STUB: not implemented"; return nil }

// GetExternalServiceCIDRs indicates an expected call of GetExternalServiceCIDRs.
func (mr *MockNetworkAPIsMockRecorder) GetExternalServiceCIDRs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLinkByMac mocks base method.
func (m *MockNetworkAPIs) GetLinkByMac(arg0 string, arg1 time.Duration) (netlink.Link, error) {
	_ = "STUB: not implemented"
	return *new(netlink.Link), nil
}

// GetLinkByMac indicates an expected call of GetLinkByMac.
func (mr *MockNetworkAPIsMockRecorder) GetLinkByMac(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRuleList mocks base method.
func (m *MockNetworkAPIs) GetRuleList(arg0 bool) ([]netlink.Rule, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRuleList indicates an expected call of GetRuleList.
func (mr *MockNetworkAPIsMockRecorder) GetRuleList(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRuleListBySrc mocks base method.
func (m *MockNetworkAPIs) GetRuleListBySrc(arg0 []netlink.Rule, arg1 net.IPNet) ([]netlink.Rule, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRuleListBySrc indicates an expected call of GetRuleListBySrc.
func (mr *MockNetworkAPIsMockRecorder) GetRuleListBySrc(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetupENINetwork mocks base method.
func (m *MockNetworkAPIs) SetupENINetwork(arg0, arg1 string, arg2 int, arg3 string, arg4 int, arg5 bool, arg6 int, arg7 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// SetupENINetwork indicates an expected call of SetupENINetwork.
func (mr *MockNetworkAPIsMockRecorder) SetupENINetwork(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetupHostNetwork mocks base method.
func (m *MockNetworkAPIs) SetupHostNetwork(arg0 []string, arg1 string, arg2 *net.IP, arg3, arg4 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// SetupHostNetwork indicates an expected call of SetupHostNetwork.
func (mr *MockNetworkAPIsMockRecorder) SetupHostNetwork(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateExternalServiceIpRules mocks base method.
func (m *MockNetworkAPIs) UpdateExternalServiceIpRules(arg0 []netlink.Rule, arg1 []string) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateExternalServiceIpRules indicates an expected call of UpdateExternalServiceIpRules.
func (mr *MockNetworkAPIsMockRecorder) UpdateExternalServiceIpRules(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateHostIptablesRules mocks base method.
func (m *MockNetworkAPIs) UpdateHostIptablesRules(arg0 []string, arg1 string, arg2 *net.IP, arg3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateHostIptablesRules indicates an expected call of UpdateHostIptablesRules.
func (mr *MockNetworkAPIsMockRecorder) UpdateHostIptablesRules(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRuleListBySrc mocks base method.
func (m *MockNetworkAPIs) UpdateRuleListBySrc(arg0 []netlink.Rule, arg1 net.IPNet) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRuleListBySrc indicates an expected call of UpdateRuleListBySrc.
func (mr *MockNetworkAPIsMockRecorder) UpdateRuleListBySrc(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UseExternalSNAT mocks base method.
func (m *MockNetworkAPIs) UseExternalSNAT() bool { _ = "STUB: not implemented"; return false }

// UseExternalSNAT indicates an expected call of UseExternalSNAT.
func (mr *MockNetworkAPIsMockRecorder) UseExternalSNAT() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRouteTableNumberForENI mocks base method.
func (m *MockNetworkAPIs) GetRouteTableNumberForENI(arg0 int, arg1 string, arg2 int, arg3 int, arg4 bool) (int, bool, error) {
	_ = "STUB: not implemented"
	return 0, false, nil
}

// GetRouteTableNumberForENI indicates an expected call of GetRouteTableNumberForENI.
func (mr *MockNetworkAPIsMockRecorder) GetRouteTableNumberForENI(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
