// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/vethwrapper (interfaces: Veth)

// Package mock_vethwrapper is a generated GoMock package.
package mock_vethwrapper

import (
	net "net"

	ns "github.com/containernetworking/plugins/pkg/ns"
	gomock "github.com/golang/mock/gomock"
)

// MockVeth is a mock of Veth interface.
type MockVeth struct {
	ctrl     *gomock.Controller
	recorder *MockVethMockRecorder
}

// MockVethMockRecorder is the mock recorder for MockVeth.
type MockVethMockRecorder struct {
	mock *MockVeth
}

// NewMockVeth creates a new mock instance.
func NewMockVeth(ctrl *gomock.Controller) *MockVeth { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeth) EXPECT() *MockVethMockRecorder {
	_ = "STUB: not implemented"

	// Setup mocks base method.
	return nil
}

func (m *MockVeth) Setup(arg0 string, arg1 int, arg2 string, arg3 ns.NetNS) (net.Interface, net.Interface, error) {
	_ = "STUB: not implemented"
	return *new(net.Interface), *new(net.Interface), nil
}

// Setup indicates an expected call of Setup.
func (mr *MockVethMockRecorder) Setup(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
