// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/eniconfig (interfaces: ENIConfig)

// Package mock_eniconfig is a generated GoMock package.
package mock_eniconfig

import (
	context "context"

	v1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/apis/crd/v1alpha1"
	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockENIConfig is a mock of ENIConfig interface.
type MockENIConfig struct {
	ctrl     *gomock.Controller
	recorder *MockENIConfigMockRecorder
}

// MockENIConfigMockRecorder is the mock recorder for MockENIConfig.
type MockENIConfigMockRecorder struct {
	mock *MockENIConfig
}

// NewMockENIConfig creates a new mock instance.
func NewMockENIConfig(ctrl *gomock.Controller) *MockENIConfig {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockENIConfig) EXPECT() *MockENIConfigMockRecorder {
	_ = "STUB: not implemented"

	// GetENIConfigName mocks base method.
	return nil
}

func (m *MockENIConfig) GetENIConfigName(arg0 context.Context, arg1 client.Client) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetENIConfigName indicates an expected call of GetENIConfigName.
func (mr *MockENIConfigMockRecorder) GetENIConfigName(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MyENIConfig mocks base method.
func (m *MockENIConfig) MyENIConfig(arg0 client.Client) (*v1alpha1.ENIConfigSpec, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MyENIConfig indicates an expected call of MyENIConfig.
func (mr *MockENIConfigMockRecorder) MyENIConfig(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
