// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/cmd/routed-eni-cni-plugin/driver (interfaces: NetworkAPIs)

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	driver "github.com/aws/amazon-vpc-cni-k8s/cmd/routed-eni-cni-plugin/driver"
	sgpp "github.com/aws/amazon-vpc-cni-k8s/pkg/sgpp"
	logger "github.com/aws/amazon-vpc-cni-k8s/pkg/utils/logger"
	gomock "github.com/golang/mock/gomock"
)

// MockNetworkAPIs is a mock of NetworkAPIs interface.
type MockNetworkAPIs struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkAPIsMockRecorder
}

// MockNetworkAPIsMockRecorder is the mock recorder for MockNetworkAPIs.
type MockNetworkAPIsMockRecorder struct {
	mock *MockNetworkAPIs
}

// NewMockNetworkAPIs creates a new mock instance.
func NewMockNetworkAPIs(ctrl *gomock.Controller) *MockNetworkAPIs {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkAPIs) EXPECT() *MockNetworkAPIsMockRecorder {
	_ = "STUB: not implemented"

	// SetupBranchENIPodNetwork mocks base method.
	return nil
}

func (m *MockNetworkAPIs) SetupBranchENIPodNetwork(arg0 driver.VirtualInterfaceMetadata, arg1 string, arg2 int, arg3, arg4 string, arg5, arg6 int, arg7 sgpp.EnforcingMode, arg8 logger.Logger) error {
	_ = "STUB: not implemented"
	return nil
}

// SetupBranchENIPodNetwork indicates an expected call of SetupBranchENIPodNetwork.
func (mr *MockNetworkAPIsMockRecorder) SetupBranchENIPodNetwork(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetupPodNetwork mocks base method.
func (m *MockNetworkAPIs) SetupPodNetwork(arg0 []driver.VirtualInterfaceMetadata, arg1 string, arg2 int, arg3 logger.Logger) error {
	_ = "STUB: not implemented"
	return nil
}

// SetupPodNetwork indicates an expected call of SetupPodNetwork.
func (mr *MockNetworkAPIsMockRecorder) SetupPodNetwork(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TeardownBranchENIPodNetwork mocks base method.
func (m *MockNetworkAPIs) TeardownBranchENIPodNetwork(arg0 driver.VirtualInterfaceMetadata, arg1 int, arg2 sgpp.EnforcingMode, arg3 logger.Logger) error {
	_ = "STUB: not implemented"
	return nil
}

// TeardownBranchENIPodNetwork indicates an expected call of TeardownBranchENIPodNetwork.
func (mr *MockNetworkAPIsMockRecorder) TeardownBranchENIPodNetwork(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TeardownPodNetwork mocks base method.
func (m *MockNetworkAPIs) TeardownPodNetwork(arg0 []driver.VirtualInterfaceMetadata, arg1 logger.Logger) error {
	_ = "STUB: not implemented"
	return nil
}

// TeardownPodNetwork indicates an expected call of TeardownPodNetwork.
func (mr *MockNetworkAPIsMockRecorder) TeardownPodNetwork(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
