// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/awsutils (interfaces: APIs)

// Package mock_awsutils is a generated GoMock package.
package mock_awsutils

import (
	context "context"
	net "net"

	awsutils "github.com/aws/amazon-vpc-cni-k8s/pkg/awsutils"
	datastore "github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd/datastore"
	vpc "github.com/aws/amazon-vpc-cni-k8s/pkg/vpc"
	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIs is a mock of APIs interface.
type MockAPIs struct {
	ctrl     *gomock.Controller
	recorder *MockAPIsMockRecorder
}

// MockAPIsMockRecorder is the mock recorder for MockAPIs.
type MockAPIsMockRecorder struct {
	mock *MockAPIs
}

// NewMockAPIs creates a new mock instance.
func NewMockAPIs(ctrl *gomock.Controller) *MockAPIs { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIs) EXPECT() *MockAPIsMockRecorder {
	_ = "STUB: not implemented"

	// AllocENI mocks base method.
	return nil
}

func (m *MockAPIs) AllocENI(arg0 context.Context, arg1 []*string, arg2 string, arg3, arg4 int) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// AllocENI indicates an expected call of AllocENI.
func (mr *MockAPIsMockRecorder) AllocENI(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AllocIPAddress mocks base method.
func (m *MockAPIs) AllocIPAddress(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// AllocIPAddress indicates an expected call of AllocIPAddress.
func (mr *MockAPIsMockRecorder) AllocIPAddress(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AllocIPAddresses mocks base method.
func (m *MockAPIs) AllocIPAddresses(arg0 context.Context, arg1 string, arg2 int) (*ec2.AssignPrivateIpAddressesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AllocIPAddresses indicates an expected call of AllocIPAddresses.
func (mr *MockAPIsMockRecorder) AllocIPAddresses(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AllocIPv6Prefixes mocks base method.
func (m *MockAPIs) AllocIPv6Prefixes(arg0 context.Context, arg1 string) ([]*string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AllocIPv6Prefixes indicates an expected call of AllocIPv6Prefixes.
func (mr *MockAPIsMockRecorder) AllocIPv6Prefixes(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeallocIPAddresses mocks base method.
func (m *MockAPIs) DeallocIPAddresses(arg0 context.Context, arg1 string, arg2 []string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeallocIPAddresses indicates an expected call of DeallocIPAddresses.
func (mr *MockAPIsMockRecorder) DeallocIPAddresses(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeallocPrefixAddresses mocks base method.
func (m *MockAPIs) DeallocPrefixAddresses(arg0 context.Context, arg1 string, arg2 []string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeallocPrefixAddresses indicates an expected call of DeallocPrefixAddresses.
func (mr *MockAPIsMockRecorder) DeallocPrefixAddresses(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeAllENIs mocks base method.
func (m *MockAPIs) DescribeAllENIs(arg0 context.Context) (awsutils.DescribeAllENIsResult, error) {
	_ = "STUB: not implemented"
	return *new(awsutils.DescribeAllENIsResult), nil
}

// DescribeAllENIs indicates an expected call of DescribeAllENIs.
func (mr *MockAPIsMockRecorder) DescribeAllENIs(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FetchInstanceTypeLimits mocks base method.
func (m *MockAPIs) FetchInstanceTypeLimits(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// FetchInstanceTypeLimits indicates an expected call of FetchInstanceTypeLimits.
func (mr *MockAPIsMockRecorder) FetchInstanceTypeLimits(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FreeENI mocks base method.
func (m *MockAPIs) FreeENI(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// FreeENI indicates an expected call of FreeENI.
func (mr *MockAPIsMockRecorder) FreeENI(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAttachedENIs mocks base method.
func (m *MockAPIs) GetAttachedENIs() ([]awsutils.ENIMetadata, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAttachedENIs indicates an expected call of GetAttachedENIs.
func (mr *MockAPIsMockRecorder) GetAttachedENIs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetENIIPv4Limit mocks base method.
func (m *MockAPIs) GetENIIPv4Limit() int { _ = "STUB: not implemented"; return 0 }

// GetENIIPv4Limit indicates an expected call of GetENIIPv4Limit.
func (mr *MockAPIsMockRecorder) GetENIIPv4Limit() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetENILimit mocks base method.
func (m *MockAPIs) GetENILimit() int { _ = "STUB: not implemented"; return 0 }

// GetENILimit indicates an expected call of GetENILimit.
func (mr *MockAPIsMockRecorder) GetENILimit() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetENISubnetID mocks base method.
func (m *MockAPIs) GetENISubnetID(arg0 context.Context, arg1 string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetENISubnetID indicates an expected call of GetENISubnetID.
func (mr *MockAPIsMockRecorder) GetENISubnetID(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetIPv4PrefixesFromEC2 mocks base method.
func (m *MockAPIs) GetIPv4PrefixesFromEC2(arg0 context.Context, arg1 string) ([]types.Ipv4PrefixSpecification, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIPv4PrefixesFromEC2 indicates an expected call of GetIPv4PrefixesFromEC2.
func (mr *MockAPIsMockRecorder) GetIPv4PrefixesFromEC2(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetIPv4sFromEC2 mocks base method.
func (m *MockAPIs) GetIPv4sFromEC2(arg0 context.Context, arg1 string) ([]types.NetworkInterfacePrivateIpAddress, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIPv4sFromEC2 indicates an expected call of GetIPv4sFromEC2.
func (mr *MockAPIsMockRecorder) GetIPv4sFromEC2(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetIPv6PrefixesFromEC2 mocks base method.
func (m *MockAPIs) GetIPv6PrefixesFromEC2(arg0 context.Context, arg1 string) ([]types.Ipv6PrefixSpecification, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIPv6PrefixesFromEC2 indicates an expected call of GetIPv6PrefixesFromEC2.
func (mr *MockAPIsMockRecorder) GetIPv6PrefixesFromEC2(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInstanceHypervisorFamily mocks base method.
func (m *MockAPIs) GetInstanceHypervisorFamily() string { _ = "STUB: not implemented"; return "" }

// GetInstanceHypervisorFamily indicates an expected call of GetInstanceHypervisorFamily.
func (mr *MockAPIsMockRecorder) GetInstanceHypervisorFamily() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInstanceID mocks base method.
func (m *MockAPIs) GetInstanceID() string { _ = "STUB: not implemented"; return "" }

// GetInstanceID indicates an expected call of GetInstanceID.
func (mr *MockAPIsMockRecorder) GetInstanceID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetInstanceType mocks base method.
func (m *MockAPIs) GetInstanceType() string { _ = "STUB: not implemented"; return "" }

// GetInstanceType indicates an expected call of GetInstanceType.
func (mr *MockAPIsMockRecorder) GetInstanceType() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLocalIPv4 mocks base method.
func (m *MockAPIs) GetLocalIPv4() net.IP { _ = "STUB: not implemented"; return *new(net.IP) }

// GetLocalIPv4 indicates an expected call of GetLocalIPv4.
func (mr *MockAPIsMockRecorder) GetLocalIPv4() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetLocalIPv6 mocks base method.
func (m *MockAPIs) GetLocalIPv6() net.IP { _ = "STUB: not implemented"; return *new(net.IP) }

// GetLocalIPv6 indicates an expected call of GetLocalIPv6.
func (mr *MockAPIsMockRecorder) GetLocalIPv6() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetNetworkCards mocks base method.
func (m *MockAPIs) GetNetworkCards() []vpc.NetworkCard { _ = "STUB: not implemented"; return nil }

// GetNetworkCards indicates an expected call of GetNetworkCards.
func (mr *MockAPIsMockRecorder) GetNetworkCards() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPrimaryENI mocks base method.
func (m *MockAPIs) GetPrimaryENI() string { _ = "STUB: not implemented"; return "" }

// GetPrimaryENI indicates an expected call of GetPrimaryENI.
func (mr *MockAPIsMockRecorder) GetPrimaryENI() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetPrimaryENImac mocks base method.
func (m *MockAPIs) GetPrimaryENImac() string { _ = "STUB: not implemented"; return "" }

// GetPrimaryENImac indicates an expected call of GetPrimaryENImac.
func (mr *MockAPIsMockRecorder) GetPrimaryENImac() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVPCIPv4CIDRs mocks base method.
func (m *MockAPIs) GetVPCIPv4CIDRs() ([]string, error) { _ = "STUB: not implemented"; return nil, nil }

// GetVPCIPv4CIDRs indicates an expected call of GetVPCIPv4CIDRs.
func (mr *MockAPIsMockRecorder) GetVPCIPv4CIDRs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVPCIPv6CIDRs mocks base method.
func (m *MockAPIs) GetVPCIPv6CIDRs() ([]string, error) { _ = "STUB: not implemented"; return nil, nil }

// GetVPCIPv6CIDRs indicates an expected call of GetVPCIPv6CIDRs.
func (mr *MockAPIsMockRecorder) GetVPCIPv6CIDRs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVpcSubnets mocks base method.
func (m *MockAPIs) GetVpcSubnets(arg0 context.Context) ([]types.Subnet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcSubnets indicates an expected call of GetVpcSubnets.
func (mr *MockAPIsMockRecorder) GetVpcSubnets(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InitCachedPrefixDelegation mocks base method.
func (m *MockAPIs) InitCachedPrefixDelegation(arg0 bool) { _ = "STUB: not implemented"; return }

// InitCachedPrefixDelegation indicates an expected call of InitCachedPrefixDelegation.
func (mr *MockAPIsMockRecorder) InitCachedPrefixDelegation(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsTrunkingCompatible mocks base method.
func (m *MockAPIs) IsTrunkingCompatible() bool { _ = "STUB: not implemented"; return false }

// IsTrunkingCompatible indicates an expected call of IsTrunkingCompatible.
func (mr *MockAPIsMockRecorder) IsTrunkingCompatible() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsEfaOnlyENI mocks base method.
func (m *MockAPIs) IsEfaOnlyENI(arg0 int, arg1 string) bool {
	_ = "STUB: not implemented"
	return false
}

// IsEfaOnlyENI indicates an expected call of IsEfaOnlyENI.
func (mr *MockAPIsMockRecorder) IsEfaOnlyENI(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsPrefixDelegationSupported mocks base method.
func (m *MockAPIs) IsPrefixDelegationSupported() bool { _ = "STUB: not implemented"; return false }

// IsPrefixDelegationSupported indicates an expected call of IsPrefixDelegationSupported.
func (mr *MockAPIsMockRecorder) IsPrefixDelegationSupported() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsPrimaryENI mocks base method.
func (m *MockAPIs) IsPrimaryENI(arg0 string) bool { _ = "STUB: not implemented"; return false }

// IsPrimaryENI indicates an expected call of IsPrimaryENI.
func (mr *MockAPIsMockRecorder) IsPrimaryENI(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsSubnetExcluded mocks base method.
func (m *MockAPIs) IsSubnetExcluded(arg0 context.Context, arg1 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsSubnetExcluded indicates an expected call of IsSubnetExcluded.
func (mr *MockAPIsMockRecorder) IsSubnetExcluded(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsUnmanagedENI mocks base method.
func (m *MockAPIs) IsUnmanagedENI(arg0 string) bool { _ = "STUB: not implemented"; return false }

// IsUnmanagedENI indicates an expected call of IsUnmanagedENI.
func (mr *MockAPIsMockRecorder) IsUnmanagedENI(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsUnmanagedNIC mocks base method.
func (m *MockAPIs) IsUnmanagedNIC(arg0 int) bool { _ = "STUB: not implemented"; return false }

// IsUnmanagedNIC indicates an expected call of IsUnmanagedNIC.
func (mr *MockAPIsMockRecorder) IsUnmanagedNIC(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RefreshCustomSGIDs mocks base method.
func (m *MockAPIs) RefreshCustomSGIDs(arg0 context.Context, arg1 *datastore.DataStoreAccess) error {
	_ = "STUB: not implemented"
	return nil
}

// RefreshCustomSGIDs indicates an expected call of RefreshCustomSGIDs.
func (mr *MockAPIsMockRecorder) RefreshCustomSGIDs(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RefreshSGIDs mocks base method.
func (m *MockAPIs) RefreshSGIDs(arg0 context.Context, arg1 string, arg2 *datastore.DataStoreAccess) error {
	_ = "STUB: not implemented"
	return nil
}

// RefreshSGIDs indicates an expected call of RefreshSGIDs.
func (mr *MockAPIsMockRecorder) RefreshSGIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetEFAOnlyENIs mocks base method.
func (m *MockAPIs) SetEFAOnlyENIs(arg0 []string) { _ = "STUB: not implemented"; return }

// SetEFAOnlyENIs indicates an expected call of SetEFAOnlyENIs.
func (mr *MockAPIsMockRecorder) SetEFAOnlyENIs(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUnmanagedENIs mocks base method.
func (m *MockAPIs) SetUnmanagedENIs(arg0 []string) { _ = "STUB: not implemented"; return }

// SetUnmanagedENIs indicates an expected call of SetUnmanagedENIs.
func (mr *MockAPIsMockRecorder) SetUnmanagedENIs(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUnmanagedNetworkCards mocks base method.
func (m *MockAPIs) SetUnmanagedNetworkCards(arg0 []bool) { _ = "STUB: not implemented"; return }

// SetUnmanagedNetworkCards indicates an expected call of SetUnmanagedNetworkCards.
func (mr *MockAPIsMockRecorder) SetUnmanagedNetworkCards(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TagENI mocks base method.
func (m *MockAPIs) TagENI(arg0 context.Context, arg1 string, arg2 map[string]string) error {
	_ = "STUB: not implemented"
	return nil
}

// TagENI indicates an expected call of TagENI.
func (mr *MockAPIsMockRecorder) TagENI(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForENIAndIPsAttached mocks base method.
func (m *MockAPIs) WaitForENIAndIPsAttached(arg0 string, arg1 int) (awsutils.ENIMetadata, error) {
	_ = "STUB: not implemented"
	return *new(awsutils.ENIMetadata), nil
}

// WaitForENIAndIPsAttached indicates an expected call of WaitForENIAndIPsAttached.
func (mr *MockAPIsMockRecorder) WaitForENIAndIPsAttached(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
