// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/containernetworking/plugins/pkg/ns (interfaces: NetNS)

// Package mock_ns is a generated GoMock package.
package mock_ns

import (
	ns "github.com/containernetworking/plugins/pkg/ns"
	gomock "github.com/golang/mock/gomock"
)

// MockNetNS is a mock of NetNS interface.
type MockNetNS struct {
	ctrl     *gomock.Controller
	recorder *MockNetNSMockRecorder
}

// MockNetNSMockRecorder is the mock recorder for MockNetNS.
type MockNetNSMockRecorder struct {
	mock *MockNetNS
}

// NewMockNetNS creates a new mock instance.
func NewMockNetNS(ctrl *gomock.Controller) *MockNetNS { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetNS) EXPECT() *MockNetNSMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockNetNS) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockNetNSMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Do mocks base method.
func (m *MockNetNS) Do(arg0 func(ns.NetNS) error) error { _ = "STUB: not implemented"; return nil }

// Do indicates an expected call of Do.
func (mr *MockNetNSMockRecorder) Do(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Fd mocks base method.
func (m *MockNetNS) Fd() uintptr { _ = "STUB: not implemented"; return 0 }

// Fd indicates an expected call of Fd.
func (mr *MockNetNSMockRecorder) Fd() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Path mocks base method.
func (m *MockNetNS) Path() string { _ = "STUB: not implemented"; return "" }

// Path indicates an expected call of Path.
func (mr *MockNetNSMockRecorder) Path() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Set mocks base method.
func (m *MockNetNS) Set() error { _ = "STUB: not implemented"; return nil }

// Set indicates an expected call of Set.
func (mr *MockNetNSMockRecorder) Set() *gomock.Call { _ = "STUB: not implemented"; return nil }
