// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/procsyswrapper (interfaces: ProcSys)

// Package mock_procsyswrapper is a generated GoMock package.
package mock_procsyswrapper

import (
	gomock "github.com/golang/mock/gomock"
)

// MockProcSys is a mock of ProcSys interface.
type MockProcSys struct {
	ctrl     *gomock.Controller
	recorder *MockProcSysMockRecorder
}

// MockProcSysMockRecorder is the mock recorder for MockProcSys.
type MockProcSysMockRecorder struct {
	mock *MockProcSys
}

// NewMockProcSys creates a new mock instance.
func NewMockProcSys(ctrl *gomock.Controller) *MockProcSys { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcSys) EXPECT() *MockProcSysMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockProcSys) Get(arg0 string) (string, error) { _ = "STUB: not implemented"; return "", nil }

// Get indicates an expected call of Get.
func (mr *MockProcSysMockRecorder) Get(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockProcSys) Set(arg0, arg1 string) error { _ = "STUB: not implemented"; return nil }

// Set indicates an expected call of Set.
func (mr *MockProcSysMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
