// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//      http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package ipamd

import (
	"net/http"
)

const (
	// defaultIntrospectionAddress is listening on localhost 61679 for ipamd introspection
	defaultIntrospectionBindAddress = "127.0.0.1:61679"

	// Environment variable to define the bind address for the introspection endpoint
	introspectionBindAddress = "INTROSPECTION_BIND_ADDRESS"
)

type rootResponse struct {
	AvailableCommands []string
}

// LoggingHandler is a object for handling http request
type LoggingHandler struct {
	h http.Handler
}

func (lh LoggingHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// ServeIntrospection sets up ipamd introspection endpoints
func (c *IPAMContext) ServeIntrospection() { _ = "STUB: not implemented"; return }

func (c *IPAMContext) setupIntrospectionServer() *http.Server {
	_ = "STUB: not implemented"
	return nil
}

// Autogenerated list of the above serverFunctions paths

// Log all requests and then pass through to serveMux

func eniV1RequestHandler(ipam *IPAMContext) func(http.ResponseWriter, *http.Request) {
	_ = "STUB: not implemented"
	return nil
}

func eniConfigRequestHandler(ipam *IPAMContext) func(http.ResponseWriter, *http.Request) {
	_ = "STUB: not implemented"
	return nil
}

func networkEnvV1RequestHandler() func(http.ResponseWriter, *http.Request) {
	_ = "STUB: not implemented"
	return nil
}

func ipamdEnvV1RequestHandler() func(http.ResponseWriter, *http.Request) {
	_ = "STUB: not implemented"
	return nil
}

func logErr(_ int, err error) { _ = "STUB: not implemented"; return }
